services:
  address-verifier:
    container_name: address-verifier
    build:
      context: .
      dockerfile: AddressVerifier/Dockerfile
    ports:
      - "8085:8085"
	environment:
		LINZ_API_LEY: ${LINZ_API_KEY}
