services:
  address-verifier:
    image: address-verifier
    build:
      context: .
      dockerfile: AddressVerifier/Dockerfile
    ports:
      - "8085:8085"
    environment:
      LINZ_API_KEY: ${LINZ_API_KEY}