name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - deploy-to-aws-eb
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    # - name: Build with Maven
    #   run: mvn clean package -DskipTests
    
    - name: Build with Gradle
      working-directory: ./AddressVerifier
      run: ./gradlew clean build
    
    - name: Configure Elastic Beanstalk Environment Variables
      run: |
        aws elasticbeanstalk update-environment \
          --application-name "${{ secrets.EB_APPLICATION_NAME }}" \
          --environment-name "${{ secrets.EB_ENVIRONMENT_NAME }}" \
          --option-settings \
            "Namespace=aws:elasticbeanstalk:application:environment,OptionName=LINZ_API_KEY,Value=${{ secrets.LINZ_API_KEY }}" \
            "Namespace=aws:elasticbeanstalk:application:environment,OptionName=VALID_API_KEYS,Value=${{ secrets.VALID_API_KEYS }}" \
            "Namespace=aws:elasticbeanstalk:application:environment,OptionName=ADMIN_PASSWORD,Value=${{ secrets.ADMIN_PASSWORD }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.EB_APPLICATION_NAME }}
        environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: ${{ secrets.AWS_REGION }}
        deployment_package: AddressVerifier/build/libs/AddressVerifier.jar
    
    - name: Deployment Success
      run: |
        echo "âœ… Application deployed successfully!"
        echo "Version: ${{ github.sha }}"
